### ISSUE TITLE
How to retrieve data from the fields?

### ISSUE THREAD

**Issue by BallisticPain** [CardJs/CardJs#10]
The documentation shows how to "start" using it, but doesn't show how to complete the process. It seems that it solely relies on form submission to transfer the data... this would be helpful to be documented. I looked into the source code, and there doesn't seem to be any methods that "get" the data from the fields for an AJAX post.

**Comment by colin-stannard** [comment]
Added get value functionality, add further examples and extend readme. As of v1.0.11 9489130

**Comment by BallisticPain** [comment]
Thanks!
