### ISSUE TITLE
check expire year

### ISSUE THREAD

**Issue by slaxnasa** [CardJs/CardJs#11]
Perfect project,

Please add a function to check if the expire-cc-year < 2016
for example : if I put 03/2015 (this is not correct year beacause we have 2016 today)

Why we have a jQuery post function with url https://cardjs.co.uk/beacon in your card-js.min.js

Best regards

**Comment by colin-stannard** [comment]
Feature added as of v1.0.12 1ae89db

You can also validate a card expiry date using the CardJs static function `CardJs.isExpiryValid`

``` javascript
var valid = CardJs.isExpiryValid(month, year);
```

Beacon is part of an upcoming feature - temporarily removed as not in use yet.
