### ISSUE TITLE
"Visa Electron" card type detection.

### ISSUE THREAD

**Issue by pandymic** [CardJs/CardJs#12]
I've come across a slight issue in the **card-js.js** file that I'd like to call to your attention. Specifically, in the `cardTypeFromNumber` function, beginning at line 394.

The very first conditional statement that matches Visa will break the procedural flow out of the function, returning "Visa". The interpreter will never get down to lines 432-434 where the "Visa Electron" card is identified, as the previous regular expression pattern has already been matched.

I would recommend moving the "Visa Electron" check before the more generic "Visa" check, which would then function as more of a catch-all.

**Comment by colin-stannard** [comment]
Thanks for that - I think I've got the order right now.

Fixed as of v1.0.13 3c48ebc

**Comment by pandymic** [comment]
Initially super confused since the commit you linked goes to updates to the README.md file. But I can confirm the updated card-js.js file in master.

I think you meant https://github.com/CardJs/CardJs/commit/0d751d794b7670813feb086765e0a7755765f0c6 ;)

Great idea listing the patterns in increasing(ish...) numerical order. Keeps things looking tidy!
