### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by okydk** [CardJs/CardJs#17]
Would be nice to have native NPM support in addition to Bower. :)
It should only take a couple of minutes to submit, and card-js is available.

**Comment by colin-stannard** [comment]
Done and done. https://www.npmjs.com/package/card-js

`npm install card-js`

**Comment by RyanQuey** [comment]
Can you give an example of how to import this module in the js code after installing via npm? (Particularly, I'm getting `jQuery is not defined` no matter what I try)
