### ISSUE TITLE
Does not accept any input from the number-pad on 101key keyboards

### ISSUE THREAD

**Issue by mystica555** [CardJs/CardJs#2]
I tried the demo; it totally ignores everything typed on the number-keys on my 101key keyboard. Regardless of numlock on or off, they are ignored.

The number keys above the qwertyuiop row work fine. 

This is not very useful...

**Comment by colin-stannard** [comment]
Should now be fixed as of 869f0dbb458e879c8442aad1092ea76a5cb1a0db v1.0.6
