### ISSUE TITLE
Change events doesn't work on fields

### ISSUE THREAD

**Issue by rpotter9** [CardJs/CardJs#24]
Awesome library, really love how clean and slick it is, just come across one problem that's all!

It looks like your library takes control of the .change, .keyup, .keydown events as when I try to update a custom input field when there has been a change in the card-number input field for example, it doesn't work at all.

I used this bit of code in Example 4 of your examples:

```javascript 
$("#card-number-1").change(function() {
        console.log("Hello World!");
      });
```

So in theory, should spit out the logging in console but does absolutely nothing.

I think lines [916-922](https://github.com/CardJs/CardJs/blob/master/src/js/card-js.js#L916-L922) is the issue:
```javascript 
this.cardNumberInput.keydown(function(e) {
    CardJs.handleCreditCardNumberKey(e, $this.creditCardNumberMask);
  });
 this.cardNumberInput.keyup(function(e) {
    $this.refreshCreditCardTypeIcon();
  });
 this.cardNumberInput.change(CardJs.handleCreditCardNumberChange);
```

Not sure how to work around this.

**Comment by pandymic** [comment]
The modified example code that you've provided, according to its selector, appears to be binding the 'change' event to the output field presented in the example, not the card-number input field.

This library does not hijack events of any existing DOM elements or how they are handled. You should be able to hook your own event bindings into the input elements. The one exception is the "Expiry Date" fields, which are re-created forcibly by the library when it is initialized (#16). Even so, you can still bind your own events, however the hook will have to be initialized after the library has loaded.

In keeping with the theme of using Example 4, this code will have your intended functionality:

```javascript
$( '#my-card-1 .card-number' ).keyup( function( e ) { 
  console.log( 'Hello World!' ); 
} );
```
Or
```javascript
$( '#my-card-1' ).data( 'cardjs' ).cardNumberInput.keyup( function( e ) { 
  console.log( 'Hello World!' ); 
} );
```

Note the nature of the "[change](https://developer.mozilla.org/en-US/docs/Web/Events/change)" and "[keypress](https://developer.mozilla.org/en-US/docs/Web/Events/keypress)"events and the conditions under which they are triggered combined with how CardJs handles the rewriting of the masked number means that they will not fire. Both `keyup` and `keydown` will fire as expected.

**Comment by rpotter9** [comment]
Ah that makes sense.

I did a bit of debugging with this and noticed how keypress wouldn't work but keyup & keydown would. I looked up why they act different and understand now.

Thanks for your help @pandymic!
