### ISSUE TITLE
broken link for cards.png image in css

### ISSUE THREAD

**Issue by BryDye** [CardJs/CardJs#3]
In the file card-type-icon.css, the css background element for:
  .card-js .card-number-wrapper .card-type-icon {
has
  background: url("https://cardjs.co.uk/card-js/css/cards.png") no-repeat 0px 23px;

Problem is that the referenced file does not exist at that link.

Going to that url in a browser gives a Laravel NotFoundHttpException error.

**Comment by colin-stannard** [comment]
Fixed as of v1.0.7 (007125df0f219ed2adab1a6c08ebea12bd90fd87) to use new image file.

Also restored https://cardjs.co.uk/card-js/css/cards.png for legacy support.
