### ISSUE TITLE
Different card formatting mask for Amex

### ISSUE THREAD

**Issue by AxelTheGerman** [CardJs/CardJs#6]
Hi,
nice job on this little library. Easy to use and no major issues so far 😎 

I noticed that Amex wants to be extra special and has a different card pattern (4-6-5) - as does Diners Club (4-4-4-2) but that works with the standard mask. See https://stripe.com/docs/testing#cards

Would be nice if the mask would automatically change based on the detected type, probably quite easy to do.

What do you think?

**Comment by colin-stannard** [comment]
Good idea. Card number formatting and CVC length are now auto adjusted based on the detected card type as of v1.0.8 (e56c260537dd0a58bfb8c2b603c01bb79a4722a4)

Thanks

**Comment by AxelTheGerman** [comment]
right on! 
big thanks for the super quick implementation - already mentally prepared myself to have to submit a PR
