### ISSUE TITLE
Diners - Carte Blanche card detection

### ISSUE THREAD

**Issue by vshkrebtii** [CardJs/CardJs#9]
**Diners - Carte Blanche** cards never will be matched, because **Diners**'s regExp will match that.

CardJs.cardTypeFromNumber = function(number) {
...
  // Diners
  re = new RegExp("^(30|36|38)");
  if (number.match(re) != null)
    return "Diners";

  // Diners - Carte Blanche
  re = new RegExp("^30[0-5]");
  if (number.match(re) != null)
    return "Diners - Carte Blanche";
...
};

**Comment by colin-stannard** [comment]
Should now be fixed as of v1.0.10 8bb9a11916e7f7ce5aa1f4c2c98d58aa39f279f8

Thanks!
